language: rust
sudo: false
cache: cargo

addons:
  apt:
    update: true
    packages:
      - valgrind

script: 
  - cargo build --all --verbose
  - cargo test --all --verbose
  - cargo doc --all --verbose
    # Check that the (non-blacklisted) examples and tests don't have memory bugs
  - python3 ./scripts/valgrind.py

before_deploy:
  - cargo doc --all --verbose
  - echo '<meta http-equiv="refresh" content="0; url=libsignal_protocol/index.html" /> ' > target/doc/index.html
  - cp -r target/doc public

matrix:
  include:
    - rust: stable
    - rust: 1.34.0
    - rust: nightly
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt --all -- --check
        - cargo clippy -- -D clippy::all

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  local_dir: public
  on:
    branch: master
    # nightly gives us better docs (intra-doc links)
    condition: "$TRAVIS_RUST_VERSION == nightly"
