[package]
name = "libsignal-protocol"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
libsignal-protocol-sys = { path = "../libsignal-protocol-sys/" }
failure = "0.1.5"
failure_derive = "0.1.5"
rand = "0.6.5"
