on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

env:
  CARGO_INCREMENTAL: 0

jobs:
  rustfmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features
      - name: Build documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace
      # Run test with feature flags in sub-directory as cargo does not support feature
      # flags in virtual workspace
      - name: Run tests (with openssl)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path libsignal-protocol/Cargo.toml --no-default-features --features=crypto-openssl
      - name: Run tests (with rust crypto)
        uses: actions-rs/cargo@v1
        with:
          working-directory: libsignal-protocol
          command: test
          args: --manifest-path libsignal-protocol/Cargo.toml --no-default-features --features=crypto-native
      - name: Install valgrind
        run: sudo apt-get install valgrind
      - name: Run valgrind (check for memory bugs)
        run: python3 ./scripts/valgrind.py
